### PR TITLE
refactoring

### PR DESCRIPTION
**Pull request by BorzdeG**
* Upgraded Kotlin version
* Replaced old dependencies: https://kotlinlang.org/docs/reference/whatsnew12.html#kotlin-standard-library-artifacts-and-split-packages
* Updated gitignore configuration

### CODE REVIEW

**Comment by Lewik** [comment]
I am using fork https://github.com/Lewik/klogging in production and will update it quickly. You could create pr.

**Comment by BorzdeG** [comment]
done: https://github.com/Lewik/klogging/pull/2

**Comment by BorzdeG** [comment]
@Lewik Is it necessary to change the dependence with "com.github.shafirov.klogging:klogging.jvm" on "com.github.lewik.klogging:klogging.jvm"? Or will there be updates in this repository?

**Comment by Lewik** [comment]
You are writing issue to `shafirov/klogging`
I didn't find any `shafirov` entry in `lewik/klogging`. If you do - send me link.

Check linkedin

**Comment by BorzdeG** [comment]
I look at https://github.com/shafirov/klogging/network or https://github.com/Lewik/klogging/network/members - the main repository at @shafirov

**Comment by Lewik** [comment]
Oh, I think I got it)
I forked **this** repo because of using this klogging in large project and sometimes (rarely to be honest) need updates, but can't wait maintainer)
So after sometime I left main repo and moved to com.github.**lewik**.klogging:klogging.jvm

I'll talk with @shafirov to get write access or fully unforked.

**Pull request closed without merging**
